### ISSUE TITLE
Deployment of multiple satellites/agents, restart master fails

### ISSUE THREAD

**Issue by jofiedler** [bodsch/ansible-icinga2#31]
Hi Bodo, when deploying multiple satellites/agents with ansible, the processing is done in parallel. At the end each one tries to restart the master, only the first one succeeds and then the error message appears:
"ERROR! The requested handler 'restart icinga2 master' was not found in either the main handlers list nor in the listening handlers list".

**Comment by jofiedler** [comment]
With the following changes it works for me locally:
secondary.yml line 103 - restart master
pki.yml line 232 - restart master

**Comment by bodsch** [comment]
Hi @jofiedler!

Thanks for your issue!
What version of the role are you using?

The handler for 'restart icinga2 master' are located her:
https://github.com/bodsch/ansible-icinga2/blob/master/handlers/main.yml#L24

this bug was fixed with 1.4.1
here the compare between 1.4.0 and the actual release
https://github.com/bodsch/ansible-icinga2/compare/1.4.0...1.4.2

**Comment by jofiedler** [comment]
Hi Bode, it works. Thanks for the fix :-)
